### ISSUE TITLE
Spillage of text in Multiple Locations

### ISSUE THREAD

**Issue by miyagami** [wchristian/kc-vita-translation#14]
In playtesting, I have found multiple text strings that need to be adjusted/reduced:

![2018-12-21-013630](https://user-images.githubusercontent.com/45841539/50377384-3f4faa00-05d1-11e9-98ad-fc2793883d9a.png)
"Ships Remaining" to "On Hand"
"Required Number of Ships" to "Max Ships"
"Materials Available" to "Available Gain"

![2018-12-22_101117](https://user-images.githubusercontent.com/45841539/50377419-e896a000-05d1-11e9-9e4d-12c368c5f74b.png)
Overflow here looks sloppy. Happens in a lot of the windows.
This window is while assigning an Escort Fleet
![2018-12-21-024444](https://user-images.githubusercontent.com/45841539/50377489-1fb98100-05d3-11e9-8b65-93a8b2a0eabd.png)
Other example, same issue, different location.

In this next one, it will be solved easily by changing a word.
![2018-12-22-001346](https://user-images.githubusercontent.com/45841539/50377437-3f9c7500-05d2-11e9-8b33-967947050af9.png)
Change: "If you have too many Ship Girls, there is a possibility of not getting a Ship Girl reward."
To         : "If you have too many Ship Girls, there is a chance of not getting a Ship Girl reward."
That should bring the tail on reward back in control.

**Comment by wchristian** [comment]
Issue 1 is fixed.

![2019-07-22 14 34 45](https://user-images.githubusercontent.com/175467/61633706-f1e30a80-ac8f-11e9-84a4-6894e90990c6.jpg)

Issue 2 is documented in #40 for later.

Issue 3 is fixed, but i don't have a screenshot for that.
