### ISSUE TITLE
Typo in Quest title?

### ISSUE THREAD

**Issue by miyagami** [wchristian/kc-vita-translation#25]
I would call this a typo, even though the Wiki says the same thing.

Southern

![2018-12-30-005142](https://user-images.githubusercontent.com/45841539/50551981-a3f8ad80-0c3e-11e9-94c0-ec07e13d1a61.png)
![2018-12-30_142432](https://user-images.githubusercontent.com/45841539/50551982-a65b0780-0c3e-11e9-96f3-24b75462e9b4.png)

**Comment by wchristian** [comment]
I've seen other typos on the wiki, so i wouldn't be surprised if it was.

**Comment by miyagami** [comment]
We can fix it.

**Comment by wchristian** [comment]
The original for this is:

> 南方連絡海域の制海権を確立せよ！

But for now i'm closing this with a reference to #10 as it's part of the "quests.xml needs work" issue.
