### ISSUE TITLE
I realize  this has likely not been supported/worked on in ages

### ISSUE THREAD

**Issue by Ironttk** [wchristian/kc-vita-translation#45]
but the installer just does not work, I've tried from the official cartridge to a online download and I cannot get the patcher to install, could you upload the files needed to patch the game somewhere so this isn't just lost to time?

**Comment by wchristian** [comment]
can you detail what exactly doesn't work? the steps in the readme should show you how to make an installer from your own game files

e: oh wait, that's the steps in the mith_readme, and the patcher here is just to modify the game ...

still, please detail what exactly doesn't work :)

**Comment by Ironttk** [comment]
Running the exe ends up failing with a 'divide by zero' error, looks to be caused by a errors when it verifies the hash, and obviously not checking the hash causes errors on the vita side. I've ordered a new memory card for the Vita, as that's just about the only thing I've not tried doing a different way.

edit
This is what looks like its constantly kicking it back.
[!]  Error! Invalid hash for: "D:\Vita\KKT\repatch\PCSG00684\Media\StreamingAssets\Xml\tables\master\mst_quest.xml"

edit2
Playing around with it more, and ignoring the hash check, I can get it to boot. Not sure what changed, but going to quests does softlock the game with no quests showing. But that was more or less expected.

**Comment by wchristian** [comment]
most important question: is your installed kc game patched to 1.02?

i verified that the translation patcher works under win10 on my system with the patched game files

mst_quest.xml should be 86215 bytes and its md5 hash should be 7f85bfcb1b4769b34974ef84787fc878

here's a full list of hashes, generated with total commander: https://gist.github.com/wchristian/fa49ddea7084d099de585c1c7ec6ae4f

if any of those don't match, and that would seem to be why the hash check fails, then the file you copied to your pc isn't the same file i got from my vita when i copied stuff

possible causes:

- a mistake in following these steps: https://github.com/wchristian/kc-vita-translation#preparation
- a mistake in documenting these steps
- a change in either of the other involved softwares
- corrupted memory card

i'm honestly very doubtful it's a hardware issue :)

**Comment by Ironttk** [comment]
I am on 1.02, and my mst_quest.xml is showing 86215 bytes. Unsure why it is giving me such an issue, if I move the original mst_quest.xml in my backup folder to my vita in the repatch, I can see the quest text untranslated. Could you send me your post patch mst_quest.xml flile?

**Comment by wchristian** [comment]
Can you generate the md5 checksum for your quest xml file?

Also, here's what should be the final product: https://www.dropbox.com/s/uo79g7k36e95nrl/mst_quest.xml?dl=1

Can you upload yours?

**Comment by Ironttk** [comment]
Sure https://www.dropbox.com/s/svrohbyex7slo2q/mst_quest.xml?dl=0 
Pulled directly from my vita. That file also works on my vita. I'm seriously unsure why/how my copy wouldn't cooperate on that file.

**Comment by wchristian** [comment]
If you open the file in a text editor you'll note that's the encrypted version of that file. :)

You must've missed a step copying the data from your vita.

**Comment by Ironttk** [comment]
I'm unsure how that got through like that as it was the only encrypted one, but its solved either way.

**Comment by wchristian** [comment]
Thanks for confirming, and good to know stuff works for you now. :)
