### ISSUE TITLE
sometimes numbers overlap the "days" indicator

### ISSUE THREAD

**Issue by wchristian** [wchristian/kc-vita-translation#9]
![image](https://user-images.githubusercontent.com/175467/50175510-4179e600-02fd-11e9-85d3-a681caa06903.png)

Repro: get ships hurt, then try to repair

Gonna have to try various permutations of patches to try and find culprit.

**Comment by miyagami** [comment]
Thank you. I will have to figure how to do that on my own soon.

Reproduced file as well:

![2018-12-17-005816](https://user-images.githubusercontent.com/45841539/50175716-6a28be00-02b2-11e9-82f9-d61b4e59da23.png)

**Comment by wchristian** [comment]
Possible fix, other ways possible too.
![image](https://user-images.githubusercontent.com/175467/50209373-dae3df00-0373-11e9-85c4-32a34aae5b34.png)

The issue is that the day marker is put into that position by way of spaces between the header and it:
```
修 復 日 数                    日
```

Easiest way is to remove it entirely, but we could also try other things, like whitespace characters with higher widths.

**Comment by miyagami** [comment]
> Easiest way is to remove it entirely, but we could also try other things, like whitespace characters with higher widths.

the only problem i see with removing the 日 Kana from it is it may throw the vertical alignment out of balance. Even so, that is much more better than is the previous overlap we were having.

**Comment by wchristian** [comment]
I'll try replacing it with a "d" soonish. :)

**Comment by wchristian** [comment]
Fixed for now. Might need to add some spaces in front of the d if it still overlaps with bigger numbers but we'll see.

The "not used" string will be translated later.

![image](https://user-images.githubusercontent.com/175467/61634576-e0026700-ac91-11e9-8758-9324cbd764e5.png)
